#ifndef ESP8266_CONFIG_H
#define ESP8266_CONFIG_H

#define ESP8266_WIFI_SSID "iQOO Neo8 Pro"
#define ESP8266_WIFI_PASSWORD "12345678"

#define ESP8266_MQTT_LINK_ID 0

#ifndef ESP8266_TEST_ENABLED
#define ESP8266_TEST_ENABLED 0
#endif

#define ONENET_MQTT_HOST "mqtts.heclouds.com"
#define ONENET_MQTT_PORT 1883
#define ONENET_PRODUCT_ID "6y0JMUFI42"
#define ONENET_DEVICE_NAME "STM32F103C8T6"
#define ONENET_MQTT_TOKEN "version=2018-10-31&res=products%2F6y0JMUFI42%2Fdevices%2FSTM32F103C8T6&et=1805693871&method=md5&sign=O69ZITSjAQuPV6pt0knEcg%3D%3D"

#define ONENET_INFO_PROID ONENET_PRODUCT_ID
#define ONENET_INFO_DEVID ONENET_DEVICE_NAME

#define ONENET_TOPIC_PROPERTY_POST "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/post"
#define ONENET_TOPIC_PROPERTY_POST_REPLY "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/post/reply"
#define ONENET_TOPIC_PROPERTY_SET "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/set"
#define ONENET_TOPIC_PROPERTY_SET_REPLY "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/set_reply"
#define ONENET_TOPIC_PROPERTY_GET "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/get"
#define ONENET_TOPIC_PROPERTY_GET_REPLY "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/get_reply"
#define ONENET_TOPIC_PROPERTY_DESIRED_GET "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/desired/get/reply"
#define ONENET_TOPIC_PROPERTY_DESIRED_DELETE "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/thing/property/desired/delete/reply"
#define ONENET_TOPIC_OTA_INFORM "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/ota/inform"
#define ONENET_TOPIC_OTA_INFORM_REPLY "$sys/" ONENET_INFO_PROID "/" ONENET_INFO_DEVID "/ota/inform_reply"

#endif
